name: "Primer Actions"
on: 
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - run: echo Hola 1
            - run: echo Hola 2
    job2:
        needs: job1
        name: Cowsays
        runs-on: ubuntu-latest
        steps:
        - name: Ship it
          uses: mscoutermarsh/cowsays-action@master
          with:
            text: 'Hola a todos!!!!'
            color: 'red'